format = """
[](white)$directory$git_branch$git_commit$git_state$git_status$time
[](white)$character """

[time]
disabled = false
format = '[$time]($style) '
time_format = "%F %T"
utc_time_offset = "local"
